{"nbformat": 4, "cells": [{"execution_count": 1, "outputs": [{"name": "stdout", "output_type": "stream", "text": "KAFKA BROKER: 172.31.15.171:9092\nSending...\nSending...\nSending...\nSending...\nSending...\nSending...\nSending...\nSending...\nSending...\nSending...\nSending...\nSending...\nSending...\nSending...\n"}, {"traceback": ["\u001b[1;31m---------------------------------------------------------------------------\u001b[0m", "\u001b[1;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)", "\u001b[1;32m<ipython-input-1-8a10f3122c4b>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m()\u001b[0m\n\u001b[0;32m     17\u001b[0m         \u001b[1;32mexcept\u001b[0m \u001b[0mLeaderNotAvailableError\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     18\u001b[0m                 \u001b[0mprint\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m'Caught a LeaderNotAvailableError. This seems to happen when auto-creating a new topic.'\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 19\u001b[1;33m         \u001b[0mtime\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0msleep\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;36m3\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     20\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n", "\u001b[1;31mKeyboardInterrupt\u001b[0m: "], "ename": "KeyboardInterrupt", "output_type": "error", "evalue": ""}], "source": "import os\nimport time\nfrom kafka import SimpleProducer, KafkaClient, KafkaConsumer\nfrom kafka.common import LeaderNotAvailableError\n\n# IP:PORT of a Kafka broker. The typical port is 9092.\nKAFKA_BROKER_IP_PORT = os.getenv('KAFKA_BROKER', '192.168.86.10:9092')\nprint(\"KAFKA BROKER: \" + KAFKA_BROKER_IP_PORT)\nkafka = KafkaClient(KAFKA_BROKER_IP_PORT)\nproducer = SimpleProducer(kafka)\n\n# Note that the application is responsible for encoding messages to type str\nwhile True:\n\tprint('Sending...')\n\ttry:\n\t\tproducer.send_messages(b\"test-topic\", b\"The medium is the message.\")\n\texcept LeaderNotAvailableError:\n\t\tprint('Caught a LeaderNotAvailableError. This seems to happen when auto-creating a new topic.')\n\ttime.sleep(3)\n\n", "metadata": {"trusted": true, "collapsed": false}, "cell_type": "code"}, {"execution_count": null, "outputs": [], "source": "", "metadata": {"trusted": true, "collapsed": true}, "cell_type": "code"}], "metadata": {"kernelspec": {"name": "python3", "language": "python", "display_name": "Python 3"}, "language_info": {"version": "3.4.0", "mimetype": "text/x-python", "nbconvert_exporter": "python", "pygments_lexer": "ipython3", "file_extension": ".py", "codemirror_mode": {"version": 3, "name": "ipython"}, "name": "python"}}, "nbformat_minor": 0}